name: Deploy Streamlit App  # Name of the workflow

on:
  push:
    branches:
      - main  # The branch that triggers the workflow

jobs:
  job_id:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      
