name: My GitHub Action Workflow

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Service Account
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT }}" > service_account.json
          export SERVICE_ACCOUNT="$(cat service_account.json)"

      - name: Deploy Streamlit App
        run: |
          streamlit run fin.py
