name: Deploy Streamlit App  # Name of the workflow

on:
  push:
    branches:
      - main  # The branch that triggers the workflow

jobs:
  deploy:  # Name of the job
    runs-on: ubuntu-latest  # Runner environment
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Action to checkout the repository code

      - name: Google Auth
        uses: 'google-github-actions/auth@v0'
        with:
          #python-version: 3.x  # Python version to set up
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}" 
          service_account: "${{ secrets.SA_EMAIL }}"

      
