name: My Job

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbdev

    - name: Run Tests
      env:
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      run: nbdev_test_nbs
